name: Index html version check

on:
  workflow_dispatch:

jobs:
  pull-and-run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull davittorchyan/my-nginx-html:latest

      - name: Run Docker container
        run: docker run -d -p 12345:80 --name test-nginx davittorchyan/my-nginx-html:latest

      - name: Wait for container start
        run: sleep 30
      - name: test index html
        run: |
          curl http://localhost:12345
          curl http://localhost:12345 > output_index.html
      - name: check diff
        run: |
          if diff index.html output_index.html &> /dev/null; then
            echo "Current version of index html is deployed"
          else 
            echo "Index html not up to date" 
            exit 1   
          fi 
